export default {
  entry: './npm/index.js',
  dest: './npm/bundles/cat-grid.umd.js',
  sourceMap: false,
  format: 'umd',
  moduleName: 'ng.cat-grid',
  external: [
    '@angular/core',
    '@angular/common',
    'rxjs/Rx',
    'rxjs/Observable',
    'rxjs/Subject',
    'rxjs/util/isArray',
    'rxjs/add/operator/map',
    'rxjs/add/operator/merge',
    'rxjs/add/operator/mergeMap',
    'rxjs/add/operator/pluck',
    'rxjs/add/operator/first',
    'rxjs/add/operator/filter',
    'rxjs/add/operator/takeUntil',
    'rxjs/add/operator/do',
    'rxjs/add/operator/partition',
    'rxjs/add/observable/fromEvent',
    'rxjs/add/observable/merge',
    'rxjs/add/observable/throw',
    'rxjs/add/observable/of',
    'ng2-dragula',
  ],
  globals: {
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    'rxjs/Rx': 'Rx',
    'rxjs/Observable': 'Rx',
    'rxjs/Subject': 'Rx',
    'rxjs/add/operator/map': 'Rx.Observable.prototype',
    'rxjs/add/operator/merge': 'Rx.Observable.prototype',
    'rxjs/add/operator/mergeMap': 'Rx.Observable.prototype',
    'rxjs/add/operator/pluck': 'Rx.Observable.prototype',
    'rxjs/add/operator/first': 'Rx.Observable.prototype',
    'rxjs/add/operator/filter': 'Rx.Observable.prototype',
    'rxjs/add/operator/takeUntil': 'Rx.Observable.prototype',
    'rxjs/add/operator/do': 'Rx.Observable.prototype',
    'rxjs/add/operator/partition': 'Rx.Observable.prototype',
    'rxjs/add/observable/fromEvent': 'Rx.Observable',
    'rxjs/add/observable/merge': 'Rx.Observable',
    'rxjs/add/observable/throw': 'Rx.Observable',
    'rxjs/add/observable/of': 'Rx.Observable',

    'rxjs/util/isArray': 'Rx.util.isArray',
    'ng2-dragula': 'ng2-dragula'
  }
}
